Bookers3/config/routes.rb
Rails.application.routes.draw do
devise_for :users
  get "top" =>"users#top"
  root to: "users#show"
  resources :books do
end
  resources :users, only: [:show, :edit, :update, :index]
end

Bookers3/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user, dependent: :destroy
	attachment :profile_image

	validates :title, presence: true
    validates :body, length: { in: 0..75 }
end

Bookers3/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         attachment :profile_image
         has_many :books, dependent: :destroy
         validates :name, length: { in: 2..75 }
end

Bookers3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	# devise_controllerは行われる前にconfigure_permitted_parametersが実行される。

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end


 before_action :authenticate_user!
  def authenticate
   redirect_to top_path unless user_signed_in?
 end
end

Bookers3/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def new
    @book = Book.new
  end

  def create
    book = Book.new(book_params)
    if book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(book)
    else
      @books = Book.all
      @book = Book
      render("books/index")
    end
  end

  def show
    @book = Book.find(params[:id])
  #   @user = User.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end


  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      flash[:notice] =  "Book was successfully updated."
      redirect_to book_path(book)
    else
      @book = book
      render("books/edit")
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
  end



  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  def user_params
  params.require(:user).permit(:name, :introduction)
  end
end

Bookers3/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
        @book = Book.new
        # @user = User.find(params[:id])
        #user一覧ページからshowリンクを押して来たときにそのユーザーに関連付いたbooksを取り出すために
        # まず@userのidを取得する必要があるのかも
        @user = User.find(params[:id])
        @books = @user.books

	end

	def edit
		@user = current_user
	end

	def index
		@users = User.all
        @book = Book.new
	end

	def update
		 @user = User.find(params[:id])
         @user.update(user_params)
         redirect_to books_path(@user.id)
	end

	private
def user_params
  params.require(:user).permit(:name, :profile_image, :introduction)
end
def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
end

Bookers3/app/helpers/users_helper.rb
module UsersHelper
end

Bookers3/app/views/books/_new.html.erb
<!-- <table class="table table-striped"> -->
<h1>New Book</h1>

<%= form_for(book) do |f| %>

  <div class="field">
    <%= f.label :title %></br>
    <%= f.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= f.label :Opinion %></br>
    <%= f.text_area :body, id: :book_body %>
  </div>

  <div class="creste">
    <%= f.submit "Create Book" , class:"btn btn-primary btn-block" %>
  </div>
<% end %>
<!-- </table> -->


<style>
  input[type="text"] {
        width: 100%;
    }

textarea{
  width: 100%;
}
</style>

Bookers3/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_for(@book) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, id: :post_body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>




<%= link_to 'Show', books_path %>
<%= link_to 'Back', books_path %>

Bookers3/app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<!-- マイページ　home ユーザーに関連付いた投稿のみを表示するペーじ -->

<div class="container">
  <div class="row">
    <div class="col-lg-3">
        <%= render "users/profile", user: current_user %>
        <%= render 'books/new', book: @book %>
      </div>
       <div class="col-lg-9">  <!-- ここを追加 -->
<table class="table table-striped">
  <h1>Books</h1>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= attachment_image_tag @user, :profile_image, :fill, 15, 15, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %></td>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.body %></td>
        <% if @user == current_user %>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>
<br>

Bookers3/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<!-- 投稿詳細 -->
<div class="container">
  <div class="row">
    <div class="col-lg-3">
    	<%= render "users/profile", user: @curent_user %>
        <%= render 'books/new', book: @book %>
      </div>
       <div class="col-lg-9">
<table class="table table-striped">

<h2> Book detail </h2>

<tr>
  <th><%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></th>
  <th><%= @book.title %></th>
  <th><%= @book.body %></th>
  <% if @user == @current_user %>
  <th><%= link_to 'Edit', edit_book_path(@book) %> </th>
  <th><%= link_to 'delete', books_path, method: :delete %></th>
  <% end %>
</tr>

</table>

Bookers3/app/views/layouts/_error_messages.html.haml
-if model.errors.any?
  .alert
    %ul
    <h3><%= @model.errors.count %> errors prohibited this obj from being saved</h3>
      -model.errors.full_messages.each do |message|
        %li= message

Bookers3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/50fc84eebf.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark mt-3 mb-3">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">Bookers</a>
        <div class="collapse navbar-collapse justify-content-end">
            <div class="navbar-right">
            <ul class="navbar-nav">
              <% if user_signed_in? %>
                <li class="nav-item active">
                    <%= link_to("Home", user_path(current_user), { class: "fas fa-home nav-link"}) %>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/users">
                    <i class="fas fa-user"></i>  Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/books">
                    <i class="fas fa-book"></i>  Boooks</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="users/sign_out">
                    <i class="fas fa-sign-in-alt"></i>  logout</a>
                </li>
                <% else %>
                <li class="nav-item">
                    <a class="nav-link" href="users/top">
                    <i class="fas fa-home"></i>  Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="users/top">
                    <i class="fas fa-link"></i>  About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="users/sign_up">
                    <i class="fas fa-edit"></i>  sign up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="users/sign_in">
                    <i class="fas fa-sign-in-alt"></i>  login</a>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
    </nav>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</header>

<body>
    <main>
      <%= yield %>
    </main>
  </body>

  <footer>
    <p class="footer-text">© CopyRight Infratop.inc</p>
  </footer>

</html>



<style>
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

.header{
  margin-top:0;
}
</style>
<!-- ヘッダーのlink_todだけ色を変える方法を探す -->







<!-- ログイン -->
<!-- <i class="fas fa-sign-in-alt"></i> -->

<!-- サインイン -->
<!-- <i class="fas fa-edit"></i> -->

<!-- アバウト -->
<!-- <i class="fas fa-link"></i> -->

Bookers3/app/views/users/_profile.html.erb
<table class="table table-striped">
<h1>User info</h1>
<div class="profile-container">
  <thead>
    <tr>
      <div class="profile-container">
<%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %>
      </div>
    </tr>

    <tr>
      <th>name</th>
      <th><div class="profile-name"><%= current_user.name %></div></th>
    </tr></div>

    <tr>
      <th>introduce</th>
      <th><div class="profile-introduction"><%= current_user.introduction %></div></th>
    </tr>

    <div>
  <!--   <button type="button" class="btn btn-primary btn-block"> -->
      <%= link_to "Edit", edit_user_path(current_user), class: "btn btn-primary btn-block" %>
  </div>

  </thead>
</div>
</table>

Bookers3/app/views/users/edit.html.erb
<!-- 投稿内容編集 -->
<table class="table table-striped">
<h1>User info</h1>
<%= form_for(@user) do |f| %>
    <label>Name</label>
     <%= f.text_field :name, id: :user_name %></br>

  <label>image</label></br>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %></br>

    <lavel>introduction</lavel>
     <%= f.text_field :introduction, id: :user_introduction %></br>

  <%= f.submit "Update User" %></br>
  <% end %>
</table>

Bookers3/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<!-- 投稿者一覧 -->

<div class="container">
  <div class="row">
    <div class="col-lg-3">
        <%= render "users/profile", user: current_user %>
        <%= render 'books/new', book: @book %>
      </div>
       <div class="col-lg-9">  <!-- ここを追加 -->
<table class="table table-striped">
  <h1>Users</h1>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 15, 15, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>
<br>

Bookers3/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-lg-3">
    	<%= render "users/profile", user: current_user %>
        <%= render 'books/new', book: @book %>
      </div>
       <div class="col-lg-9">
<table class="table table-striped">
	<h1>Books</h1>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Introduction</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
      	<td><%= attachment_image_tag user, :profile_image, :fill, 15, 15, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %></td>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
         <!-- <td><%= link_to 'Show', book_path %></td> -->
        <% if user.id == current_user.id %>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
    
  </tbody>
</table>
</div>
</div>
</div>
<br>

Bookers3/app/views/users/top.html.erb
<p id="notice"><%= notice %></p>

<h1>welcome to Bookers</h1>
<h3>In Bookers</h3>
<h3>you can share and exchange your opinions , inpressions , and emotions<br>
	about various books!</h3>

<td><%= link_to 'Log in', new_user_session_path %></td>
<td><%= link_to 'Sign Up', new_user_registration_path %></td>